### ISSUE TITLE
Panic when passenger is restarted

### ISSUE THREAD

**Issue by Sjeanpierre** [Sjeanpierre/passenger-datadog-monitor#1]
panic: runtime error: index out of range

goroutine 1 [running]:
main.summerizeStats(0xc20801e6e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/passenger-datadog-monitor/main.go:55 +0x187
main.processed(0xc2080a3f38, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/passenger-datadog-monitor/main.go:93 +0x206
main.chartProcessed(0xc2080a3f38, 0xc208056b00)
    /Users/jstevenson/src/misc/go/src/github.com/sjeanpierre/passenger-datadog-monitor/main.go:132 +0x33
main.main()
    /Users

**Comment by Sjeanpierre** [comment]
Issue is related to the code attempting to parse data that is not present

**Comment by Sjeanpierre** [comment]
Add daemon monitor like Monit to the mix to restart process if it dies

**Comment by Sjeanpierre** [comment]
add check into the code to ensure that we have data before we process anything
